In [3]:
import pandas as pd

In [4]:
df = pd.read_csv('./contents_20260213_00001.csv',sep='\t')

C:\Users\M Rohith\AppData\Local\Temp\ipykernel_22596\687564467.py:1: DtypeWarning: Columns (1,6,19,23,26,27,28,30,31,32,33,35,36,37,39) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('./contents_20260213_00001.csv',sep='\t')

In [5]:
df2 = df[(df['enriched_tmdbid'] == 'not found') & (df['enriched_imdbid'] != 'not found')].head(50)

In [6]:
df2.head(5)

,contentid,cast,contentname,contenttype,genre,imgurl,keywords,language,parentid,parentname,...,enriched_rating,enriched_imdbid,enriched_language,enriched_tmdbid,enriched_meta_status,property_tags,portrait_url,landscape_url,contentpath,enriched_keywords
1625249,3098_movie,NaN,Jobless,movie,drama,https://img1.hotstarext.com/image/upload/f_aut...,NaN,Hindi,0,NaN,...,8.9,tt14663246,Hindi,not found,Done,NaN,NaN,NaN,NaN,NaN
1625252,3111_movie,NaN,Drive,movie,thriller,https://img1.hotstarext.com/image/upload/f_aut...,NaN,Hindi,0,NaN,...,3.0,tt27431710,Hindi,not found,Done,NaN,NaN,NaN,NaN,NaN
1625254,3115_movie,NaN,Bin Bulaaye,movie,"drama,sequel,love,romance,comedy,blackcomedy",https://img1.hotstarext.com/image/upload/f_aut...,NaN,Hindi,0,NaN,...,5.1,tt10646722,Hindi,not found,Done,NaN,NaN,NaN,NaN,NaN
1625273,3196_movie,NaN,Smile Simi,movie,"family,drama",https://img1.hotstarext.com/image/upload/f_aut...,NaN,Hindi,0,NaN,...,4.0,tt21429956,Hindi,not found,Done,NaN,NaN,NaN,NaN,NaN
1625275,3351_movie,NaN,Masala Steps,movie,"drama,awardwinning,relationship",https://img1.hotstarext.com/image/upload/f_aut...,NaN,Hindi,0,NaN,...,6.4,tt11147358,Hindi,not found,Done,NaN,NaN,NaN,NaN,NaN

In [7]:
df3 = pd.read_csv(r'R:\meta_enr\contents\8GT-1Wc-vDn-SvY\20260213\contents_20260213_00001.csv')

In [8]:
df3.shape

(10612, 41)

In [9]:
df4= pd.concat([df2,df3])

In [10]:
df4.columns

Index(['contentid', 'cast', 'contentname', 'contenttype', 'genre', 'imgurl',
       'keywords', 'language', 'parentid', 'parentname', 'releaseyear',
       'status', 'enriched_meta', 'rules', 'duration', 'partnername',
       'allowedcountries', 'restrictedcountries', 'additionalproperties',
       'rating', 'releasedate', 'modified_on', 'created_on', 'director',
       'combined_genre', 'parental_rating', 'pay_type', 'enriched_genre',
       'enriched_subgenre', 'enriched_releaseyear', 'enriched_rating',
       'enriched_imdbid', 'enriched_language', 'enriched_tmdbid',
       'enriched_meta_status', 'property_tags', 'portrait_url',
       'landscape_url', 'contentpath', 'enriched_keywords', 'Unnamed: 0'],
      dtype='object')

In [11]:
print('director' in df4.columns)

True

In [16]:
df4[df4['contentid'] == '3098_movie']

,contentid,cast,contentname,contenttype,genre,imgurl,keywords,language,parentid,parentname,...,enriched_imdbid,enriched_language,enriched_tmdbid,enriched_meta_status,property_tags,portrait_url,landscape_url,contentpath,enriched_keywords,Unnamed: 0
1625249,3098_movie,NaN,Jobless,movie,drama,https://img1.hotstarext.com/image/upload/f_aut...,NaN,Hindi,0,NaN,...,tt14663246,Hindi,not found,Done,NaN,NaN,NaN,NaN,NaN,NaN
0,3098_movie,NaN,Jobless,movie,drama,https://img1.hotstarext.com/image/upload/f_aut...,NaN,Hindi,0.0,NaN,...,tt14663246,Hindi,not found,Done,NaN,NaN,NaN,NaN,NaN,0.0

In [37]:
df4.reset_index(drop=True,inplace=True)
df4.head()

,contentid,cast,contentname,contenttype,genre,imgurl,keywords,language,parentid,parentname,...,enriched_rating,enriched_imdbid,enriched_language,enriched_tmdbid,enriched_meta_status,property_tags,portrait_url,landscape_url,contentpath,enriched_keywords
0,3098_movie,NaN,Jobless,movie,drama,https://img1.hotstarext.com/image/upload/f_aut...,NaN,Hindi,0,NaN,...,8.9,tt14663246,Hindi,not found,Done,NaN,NaN,NaN,NaN,NaN
1,3111_movie,NaN,Drive,movie,thriller,https://img1.hotstarext.com/image/upload/f_aut...,NaN,Hindi,0,NaN,...,3.0,tt27431710,Hindi,not found,Done,NaN,NaN,NaN,NaN,NaN
2,3115_movie,NaN,Bin Bulaaye,movie,"drama,sequel,love,romance,comedy,blackcomedy",https://img1.hotstarext.com/image/upload/f_aut...,NaN,Hindi,0,NaN,...,5.1,tt10646722,Hindi,not found,Done,NaN,NaN,NaN,NaN,NaN
3,3196_movie,NaN,Smile Simi,movie,"family,drama",https://img1.hotstarext.com/image/upload/f_aut...,NaN,Hindi,0,NaN,...,4.0,tt21429956,Hindi,not found,Done,NaN,NaN,NaN,NaN,NaN
4,3351_movie,NaN,Masala Steps,movie,"drama,awardwinning,relationship",https://img1.hotstarext.com/image/upload/f_aut...,NaN,Hindi,0,NaN,...,6.4,tt11147358,Hindi,not found,Done,NaN,NaN,NaN,NaN,NaN

In [38]:
df4.shape

(10612, 40)

In [40]:
df4['created_on'] = "2026-02-12 16:00:00"

In [41]:
df4['created_on'].value_counts()

created_on
2026-02-12 16:00:00    10612
Name: count, dtype: int64

In [42]:
df4.to_csv(r'R:\meta_enr\contents\8GT-1Wc-vDn-SvY\20260213\contents_20260213_00001.csv')

In [25]:
df1 = df[df['enriched_imdbid'] == 'not found']

In [26]:
df1.head(50)

,contentid,cast,contentname,contenttype,genre,imgurl,keywords,language,parentid,parentname,...,enriched_rating,enriched_imdbid,enriched_language,enriched_tmdbid,enriched_meta_status,property_tags,portrait_url,landscape_url,contentpath,enriched_keywords
1371,57532_movie,"Sukhmani,Sarabjeet Dhak,Kamal Lotey,Ruth Desuz...",Hara Chura,movie,"drama,romance",https://d229kpbsb5jevy.cloudfront.net/chaupal/...,NaN,Punjabi,0.0,NaN,...,4.5,not found,Punjabi,movie/1461296,Done,NaN,https://d229kpbsb5jevy.cloudfront.net/chaupal/...,https://d229kpbsb5jevy.cloudfront.net/chaupal/...,movie/hara-chura,NaN
1372,55519_movie,"Satwinder Kaur,Jas Waraich,Gurchet Chitarkar,T...",Challe Yaar Coachella,movie,"comedy,musical",https://d229kpbsb5jevy.cloudfront.net/chaupal/...,NaN,Punjabi,0.0,NaN,...,5.0,not found,Punjabi,movie/1451523,Done,NaN,https://d229kpbsb5jevy.cloudfront.net/chaupal/...,https://d229kpbsb5jevy.cloudfront.net/chaupal/...,movie/challe-yaar-coachella,NaN
1373,20143_movie,NaN,Honey Bunny - Lost In Space,movie,"animation,children",https://d229kpbsb5jevy.cloudfront.net/sony4/64...,NaN,Hindi,0.0,NaN,...,4.0,not found,Hindi,movie/1163065-honey-bunny-lost-in-space,Done,NaN,https://d229kpbsb5jevy.cloudfront.net/sony4/36...,https://d229kpbsb5jevy.cloudfront.net/sony4/64...,movie/honey-bunny-lost-in-space,NaN
1374,25207_movie,"CS Kishan,Nandini Rai",Tantrakarma,movie,"horror,mystery,supernatural,psychiatrist,paran...",https://d229kpbsb5jevy.cloudfront.net/zee2/ima...,NaN,Hindi,0.0,NaN,...,5.0,not found,Hindi,movie/1029102-tantrakarma,Done,NaN,https://d229kpbsb5jevy.cloudfront.net/zee5/600...,https://d229kpbsb5jevy.cloudfront.net/zee2/ima...,movie/tantrakarma,NaN
1375,13419_movie,"Sandy Sandeep,Parminder Gill,Mann Rodi Ala,Jas...",Patwari,movie,"drama,farmer",https://d229kpbsb5jevy.cloudfront.net/chaupal/...,NaN,Punjabi,0.0,NaN,...,4.5,not found,Punjabi,movie/1002380,Done,NaN,https://d229kpbsb5jevy.cloudfront.net/chaupal/...,https://d229kpbsb5jevy.cloudfront.net/chaupal/...,movie/patwari,NaN
1376,25023_movie,"Ankush Hazra,Nusrat Faria",Bhoy,movie,"drama,thriller,action",https://d229kpbsb5jevy.cloudfront.net/zee2/ima...,NaN,Bangla,0.0,NaN,...,4.0,not found,Bangla,movie/841854,Done,NaN,https://d229kpbsb5jevy.cloudfront.net/zee5/600...,https://d229kpbsb5jevy.cloudfront.net/zee2/ima...,movie/bhoy-2,NaN
1377,12490_movie,"Srindaa,Viji Penkoottu",Asangadithar,movie,"womencentric,drama",https://d229kpbsb5jevy.cloudfront.net/sony4/64...,NaN,Malayalam,0.0,NaN,...,3.5,not found,Malayalam,movie/1248075-asangadithar,Done,NaN,https://d229kpbsb5jevy.cloudfront.net/sony4/36...,https://d229kpbsb5jevy.cloudfront.net/sony4/64...,movie/asangadithar,NaN
1378,15882_movie,"Ammy Sethi,Vicky Singh,Sameer Mahi,Nisha Bano",Fight For Justice,movie,"crime,drama,action,thriller,cop,police",https://d229kpbsb5jevy.cloudfront.net/chaupal/...,NaN,Punjabi,0.0,NaN,...,3.5,not found,Punjabi,movie/1209265,Done,NaN,https://d229kpbsb5jevy.cloudfront.net/chaupal/...,https://d229kpbsb5jevy.cloudfront.net/chaupal/...,movie/fight-for-justice,NaN
1379,18192_movie,"Ankush Khurana,Naginder Gakhar,Malkeet Rauni,D...",Bande Khani Bandook Nagni,movie,"drama,action",https://d229kpbsb5jevy.cloudfront.net/chaupal/...,NaN,Punjabi,0.0,NaN,...,3.0,not found,Punjabi,movie/1216490,Done,NaN,https://d229kpbsb5jevy.cloudfront.net/chaupal/...,https://d229kpbsb5jevy.cloudfront.net/chaupal/...,movie/bande-khani-bandook-nagni,NaN
1380,18182_movie,NaN,Jungle-E Sei Raat,movie,horror,https://d229kpbsb5jevy.cloudfront.net/sony4/64...,NaN,Bangla,0.0,NaN,...,3.0,not found,Bangla,movie/1248069-jungle-e-sei-raat,Done,NaN,https://d229kpbsb5jevy.cloudfront.net/sony4/36...,https://d229kpbsb5jevy.cloudfront.net/sony4/64...,movie/jungle-e-sei-raat,NaN
1381,15159_movie,NaN,Gokuldham to Galacto (Part 1),movie,"animation,children",https://d229kpbsb5jevy.cloudfront.net/sony4/64...,NaN,Hindi,0.0,NaN,...,4.2,not found,Hindi,movie/1163042-gokuldham-to-galacto,Done,NaN,https://d229kpbsb5jevy.cloudfront.net/sony4/36...,https://d229kpbsb5jevy.cloudfront.net/sony4/64...,movie/gokuldham-to-galacto-part-1,NaN
1382,23443_movie,"Guri Gill,Gurbinder Mahal,Deedar Gill,Divjot K...",Lucky Scheme,movie,"comedy,drama",https://d229kpbsb5jevy.cloudfront.net/chaupal/...,NaN,Punjabi,0.0,NaN,...,4.0,not found,Punjabi,movie/1280791,Done,NaN,https://d229kpbsb5jevy.cloudfront.net/chaupal/...,https://d229kpbsb5jevy.cloudfront.net/chaupal/...,movie/lucky-scheme,NaN
1383,32885_movie,"Prateek Singh Rai,Bhinda Aujla,Surbhi Mahendru...",Alzheimer,movie,"crime,drama",https://d229kpbsb5jevy.cloudfront.net/chaupal/...,NaN,Punjabi,0.0,NaN,...,3.3,not found,Punjabi,movie/1337708,Done,NaN,https://d229kpbsb5jevy.cloudfront.net/chaupal/...,https://d229kpbsb5jevy.cloudfront.net/chaupal/...,movie/alzheimer,NaN
1384,33905_movie,"Harwinder Singh,Sudesh Sharma,Rajni Bajaj,Kama...",Lag Gaye,movie,"comedy,drama",https://d229kpbsb5jevy.cloudfront.net/chaupal/...,NaN,Punjabi,0.0,NaN,...,4.0,not found,punjabi,movie/1336910,Done,NaN,https://d229kpbsb5jevy.cloudfront.net/chaupal/...,https://d229kpbsb5jevy.cloudfront.net/chaupal/...,movie/lag-gaye,NaN
1385,17803_movie,"Suman Banerjee,Indrakshi Nag,Diganta Saha,Ranj...",Bhootbari Forest,movie,"ghost,horror,supernatural,haunted,paranormal,d...",https://d229kpbsb5jevy.cloudfront.net/sony4/64...,NaN,Bangla,0.0,NaN,...,3.5,not found,Bangla,movie/1248985-bhootbari-forest,Done,NaN,https://d229kpbsb5jevy.cloudfront.net/sony4/36...,https://d229kpbsb5jevy.cloudfront.net/sony4/64...,movie/bhootbari-forest,NaN
1387,34795_movie,"Saira,Jaswinder Bhalla,Dilawar Sidhu,Arsh Kahl...",Daddy Samjheya Karo,movie,"comedy,drama",https://d229kpbsb5jevy.cloudfront.net/chaupal/...,NaN,Punjabi,0.0,NaN,...,5.0,not found,Punjabi,movie/1351667-daddy-samjheya-karo,Done,NaN,https://d229kpbsb5jevy.cloudfront.net/chaupal/...,https://d229kpbsb5jevy.cloudfront.net/chaupal/...,movie/daddy-samjheya-karo,NaN
1388,17780_movie,"Moumita Gupta,Shubhankar Ganguly,Jayashree Muk...",Lal Saheber Kuthi,movie,"evil,ghost,horror,haunted",https://d229kpbsb5jevy.cloudfront.net/sony4/64...,NaN,Bangla,0.0,NaN,...,3.0,not found,Bangla,movie/304366-lal-shaheber-kuthi,Done,NaN,https://d229kpbsb5jevy.cloudfront.net/sony4/36...,https://d229kpbsb5jevy.cloudfront.net/sony4/64...,movie/lal-saheber-kuthi,NaN
1389,25151_movie,"P. Ravi Shankar,Rangayana Raghu,Tabla Nani,Thi...",Kaaneyadavara Bagge Prakatane,movie,"drama,mystery,murder,thriller,comedy",https://d229kpbsb5jevy.cloudfront.net/zee2/ima...,NaN,Kannada,0.0,NaN,...,6.0,not found,Kannada,movie/1011719-kaaneyadavara-bagge-prakatane,Done,NaN,https://d229kpbsb5jevy.cloudfront.net/zee5/600...,https://d229kpbsb5jevy.cloudfront.net/zee2/ima...,movie/kaaneyadavara-bagge-prakatane,NaN
1406,3380_movie,NaN,Spirit of the Mountains,movie,"wildlife,documentary,animalsandnature",https://img1.hotstarext.com/image/upload/f_aut...,NaN,"English,Hindi,Tamil,Telugu",0.0,NaN,...,5.0,not found,english,movie/1146944,Done,NaN,NaN,NaN,NaN,NaN
1411,3145_movie,NaN,Hippodrome,movie,"sports,drama",https://img1.hotstarext.com/image/upload/f_aut...,NaN,Hindi,0.0,NaN,...,3.0,not found,Hindi,movie/1185131-hippodrome,Done,NaN,NaN,NaN,NaN,NaN
1412,3174_movie,"Kari Wahlgren,John Kahrs",Paperman,movie,"family,animation,shorts,kids,children",https://img1.hotstarext.com/image/upload/f_aut...,NaN,English,0.0,NaN,...,4.0,not found,English,movie/887077,Done,NaN,NaN,NaN,NaN,NaN
1414,25110_movie,"Buddhadeb Bhattacharjee,Aindrila Sharma,Anirba...",Bhole Baba Paar Karega,movie,"comedy,drama",https://d229kpbsb5jevy.cloudfront.net/zee2/ima...,NaN,Bangla,0.0,NaN,...,4.0,not found,Bangla,movie/1006848,Done,NaN,https://d229kpbsb5jevy.cloudfront.net/zee5/600...,https://d229kpbsb5jevy.cloudfront.net/zee2/ima...,movie/bhole-baba-paar-karega,NaN
1417,3476_movie,NaN,Killer Snakes,movie,"animalsandnature,nature,wildlife,animals,docum...",https://img1.hotstarext.com/image/upload/f_aut...,NaN,"English,Hindi,Telugu,Tamil",0.0,NaN,...,6.0,not found,english,movie/827848,Done,NaN,"https://img.hotstar.com/image/upload/f_auto,t_...",https://img1.hotstarext.com/image/upload/f_aut...,movie/killer-snakes,NaN
1449,25261_movie,"Kanchan Mullick,Ushasi Ray,Rishav Basu",Iskaboner Rani,movie,"comedy,drama,thriller",https://d229kpbsb5jevy.cloudfront.net/zee2/ima...,NaN,Bangla,0.0,NaN,...,4.0,not found,Bangla,movie/904014-iskaboner-rani,Done,NaN,https://d229kpbsb5jevy.cloudfront.net/zee5/600...,https://d229kpbsb5jevy.cloudfront.net/zee2/ima...,movie/iskaboner-rani,NaN
1450,25364_movie,"Loic Gouzer,Dianne Dwyer Modestini,Scott Reyburn",The Saviour For Sale,movie,"documentary,thriller",https://d229kpbsb5jevy.cloudfront.net/zee2/ima...,NaN,English,0.0,NaN,...,3.0,not found,English,movie/818082-salvator-mundi,Done,NaN,https://d229kpbsb5jevy.cloudfront.net/zee5/600...,https://d229kpbsb5jevy.cloudfront.net/zee2/ima...,movie/the-saviour-for-sale,NaN
1451,13404_movie,"Dr Ranjit Riaz Sharma,Sanjeev Rai,Anita Shabde...",Punjabi By Nature,movie,"drama,love,relationship,romance",https://d229kpbsb5jevy.cloudfront.net/chaupal/...,NaN,Punjabi,0.0,NaN,...,4.0,not found,Punjabi,movie/1196982,Done,NaN,https://d229kpbsb5jevy.cloudfront.net/chaupal/...,https://d229kpbsb5jevy.cloudfront.net/chaupal/...,movie/punjabi-by-nature,NaN
1452,3757_movie,NaN,Ultimate Viper: Fear The Fang,movie,"wildlife,adventure,documentary,animalsandnature",https://img1.hotstarext.com/image/upload/f_aut...,NaN,"English,Hindi,Tamil,Telugu",0.0,NaN,...,5.0,not found,English,movie/827845,Done,NaN,"https://img.hotstar.com/image/upload/f_auto,t_...",https://img1.hotstarext.com/image/upload/f_aut...,movie/ultimate-viper-fear-the-fang,NaN
1453,25330_movie,"Shoumo Bannerjee,Shreema Bhattacharjee,Partha ...",Mon Kharaper Osudh,movie,"family,comedy,drama,relationship",https://d229kpbsb5jevy.cloudfront.net/zee2/ima...,NaN,Bangla,0.0,NaN,...,5.0,not found,Bangla,movie/1080859,Done,NaN,https://d229kpbsb5jevy.cloudfront.net/zee5/600...,https://d229kpbsb5jevy.cloudfront.net/zee2/ima...,movie/mon-kharaper-osudh,NaN
1454,25334_movie,"Javed Akhtar,Kausar Munir,Kumar Vishwas,Zakir ...",India Shayari Project,movie,"musical,classical,poet",https://d229kpbsb5jevy.cloudfront.net/zee2/ima...,NaN,Hindi,0.0,NaN,...,4.0,not found,Hindi,movie/862680,Done,NaN,https://d229kpbsb5jevy.cloudfront.net/zee5/600...,https://d229kpbsb5jevy.cloudfront.net/zee2/ima...,movie/india-shayari-project,NaN
1455,25287_movie,"Koushani Ray,Somraj Maity",Phire Dekha,movie,"couple,drama,relationship,romance",https://d229kpbsb5jevy.cloudfront.net/zee2/ima...,NaN,Bangla,0.0,NaN,...,5.0,not found,Bangla,movie/1105741,Done,NaN,https://d229kpbsb5jevy.cloudfront.net/zee5/600...,https://d229kpbsb5jevy.cloudfront.net/zee2/ima...,movie/phire-dekha,NaN
1501,26180_movie,"Anamika Chakraborty,Mainak Banerjee,Dipak,Sean...",Ekta Bhalobasar Golpo,movie,"drama,romance",https://d229kpbsb5jevy.cloudfront.net/zee2/ima...,NaN,Bangla,0.0,NaN,...,3.0,not found,bangla,movie/1330363-ekta-bhalobasar-golpo,Done,NaN,https://d229kpbsb5jevy.cloudfront.net/zee2/600...,https://d229kpbsb5jevy.cloudfront.net/zee2/ima...,movie/ekta-bhalobasar-golpo,NaN
1515,25340_movie,"Mimi Dutta,Sritama Bhattacharjee,Farhan Imroze",Ami Tumi Ar Maloti,movie,"couple,comedy,relationship,romance",https://d229kpbsb5jevy.cloudfront.net/zee2/ima...,NaN,Bangla,0.0,NaN,...,4.0,not found,Bangla,movie/1000482-ami-tumi-ar-maloti,Done,NaN,https://d229kpbsb5jevy.cloudfront.net/zee5/600...,https://d229kpbsb5jevy.cloudfront.net/zee2/ima...,movie/ami-tumi-ar-maloti,NaN
1516,25377_movie,"Aman Shergill,Mink Randhawa",Chubare Wali Baari,movie,"comedy,drama,love,romance",https://d229kpbsb5jevy.cloudfront.net/zee2/ima...,NaN,Punjabi,0.0,NaN,...,4.2,not found,Punjabi,movie/813495-chubare-wali-baari-2021,Done,NaN,https://d229kpbsb5jevy.cloudfront.net/zee5/600...,https://d229kpbsb5jevy.cloudfront.net/zee2/ima...,movie/chubare-wali-baari,NaN
1581,25746_movie,"Asad Faruqi,Geeta Gandbhir,Sharmeen Obaid - Ch...",Armed with Faith,movie,"documentary,thriller",https://d229kpbsb5jevy.cloudfront.net/zee2/ima...,NaN,Hindi,0.0,NaN,...,5.0,not found,Hindi,movie/476377-armed-with-faith,Done,NaN,NaN,NaN,movie/armed-with-faith,NaN
1597,42552_movie,"Anurag Arora,Devki Rani,Diksha Lamba,Rahuvir Mann",Amma Meri,movie,drama,https://li-img-cdn-lb.lionsgateplay.com/motion...,NaN,Hindi,0.0,NaN,...,3.0,not found,Hindi,movie/732671-amma-meri,Done,NaN,https://li-img-cdn-lb.lionsgateplay.com/motion...,https://li-img-cdn-lb.lionsgateplay.com/motion...,movie/amma-meri,NaN
1662,25567_movie,"Anjana Basu,Joy Sengupta,Manasi Sinha,Arpita C...",Amar Artanad,movie,drama,https://d229kpbsb5jevy.cloudfront.net/zee2/ima...,NaN,Bangla,0.0,NaN,...,4.0,not found,Bangla,movie/1105735,Done,NaN,https://d229kpbsb5jevy.cloudfront.net/zee2/600...,https://d229kpbsb5jevy.cloudfront.net/zee2/ima...,movie/amar-artanad,NaN
1743,25917_movie,"Sanchaari Das,Saptarshi Maulik,Amandeep,Saborn...",Jayo Jayo Debi,movie,"drama,romance,love,friends,comedy,relationship",https://d229kpbsb5jevy.cloudfront.net/zee2/ima...,NaN,Bangla,0.0,NaN,...,3.0,not found,Bangla,movie/1105732-jayo-jayo-debi,Done,NaN,https://d229kpbsb5jevy.cloudfront.net/zee2/600...,https://d229kpbsb5jevy.cloudfront.net/zee2/ima...,movie/jayo-jayo-debi,NaN
1774,26024_movie,"Oindrilla Sharma,Sreema Bhattacharyya,Rishav B...",Mittir Parar Maradona,movie,"drama,romance",https://d229kpbsb5jevy.cloudfront.net/zee2/ima...,NaN,Bangla,0.0,NaN,...,4.0,not found,Bangla,movie/933077,Done,NaN,https://d229kpbsb5jevy.cloudfront.net/zee5/600...,https://d229kpbsb5jevy.cloudfront.net/zee2/ima...,movie/mittir-parar-maradona,NaN
1782,12177_movie,NaN,Honey and Bunny In Space Adventure,movie,kids,https://d229kpbsb5jevy.cloudfront.net/sony4/64...,NaN,Hindi,0.0,NaN,...,4.0,not found,Hindi,movie/844070-honey-and-bunny-in-space-adventure,Done,NaN,https://d229kpbsb5jevy.cloudfront.net/sony4/36...,https://d229kpbsb5jevy.cloudfront.net/sony4/64...,movie/honey-and-bunny-in-space-adventure,NaN
1879,26090_movie,"Jitendra Joshi,Kishor Choughule,Mangesh Kadam,...",Vastraharan,movie,"drama,comedy",https://d229kpbsb5jevy.cloudfront.net/zee2/ima...,NaN,Marathi,0.0,NaN,...,0.0,not found,Marathi,movie/597147,Done,",adult,",https://d229kpbsb5jevy.cloudfront.net/zee5/600...,https://d229kpbsb5jevy.cloudfront.net/zee2/ima...,movie/vastraharan,NaN
1880,25276_movie,"Sreeparna Roy,Manali Dey",Nimki Phulki 2,movie,"drama,family,romance,comedy,siblings",https://d229kpbsb5jevy.cloudfront.net/zee2/ima...,NaN,Bangla,0.0,NaN,...,5.0,not found,Bangla,movie/921760,Done,NaN,https://d229kpbsb5jevy.cloudfront.net/zee5/600...,https://d229kpbsb5jevy.cloudfront.net/zee2/ima...,movie/nimki-phulki-2,NaN
1881,25252_movie,"Gourab Chatterjee,Devlina Kumar,Beas Dhar,Budd...",Ekti Bangali Alien Er Golpo,movie,drama,https://d229kpbsb5jevy.cloudfront.net/zee2/ima...,NaN,Bangla,0.0,NaN,...,4.0,not found,Bangla,movie/915509,Done,NaN,https://d229kpbsb5jevy.cloudfront.net/zee5/600...,https://d229kpbsb5jevy.cloudfront.net/zee2/ima...,movie/ekti-bangali-alien-er-golpo,NaN
1910,2516_movie,NaN,Wild Alaska: Arctic Summer,movie,"animalsandnature,nature,wildlife,animals,docum...",https://img1.hotstarext.com/image/upload/f_aut...,NaN,"English,Hindi,Tamil,Telugu",0.0,NaN,...,4.2,not found,english,movie/894624-wild-alaska-arctic-summer,Done,NaN,"https://img.hotstar.com/image/upload/f_auto,t_...",https://img1.hotstarext.com/image/upload/f_aut...,movie/wild-alaska-arctic-summer,NaN
1986,3699_movie,NaN,Mangalyaan: India's Mission To Mars,movie,documentary,https://img1.hotstarext.com/image/upload/f_aut...,NaN,"English,Hindi,Bangla,Tamil,Telugu",0.0,NaN,...,4.0,not found,english,movie/1067762-mangalyaan-india-s-mission-to-mars,Done,NaN,NaN,NaN,NaN,NaN
1990,3782_movie,NaN,Operation Elephant,movie,"wildlife,documentary,animalsandnature",https://img1.hotstarext.com/image/upload/f_aut...,NaN,"English,Hindi,Tamil,Telugu",0.0,NaN,...,4.5,not found,english,movie/1162615-operation-elephant,Done,NaN,NaN,NaN,NaN,NaN
2017,13352_movie,"Raj Dhaliwal,Harwinder Singh Aujla,Siddhi Rath...",Maila Rabb,movie,"social,drama,socialmessage",https://images.chaupal.tv/dcbfdb302e6905b1acc1...,NaN,Punjabi,0.0,NaN,...,3.5,not found,Punjabi,movie/915882-maila-rabb,Done,NaN,NaN,NaN,NaN,NaN
2018,16328_movie,NaN,Inside NSG,movie,"patriotic,inspirational,patriotism,army,docume...",https://img1.hotstarext.com/image/upload/f_aut...,NaN,"English,Hindi,Bangla,Tamil,Kannada,Telugu",0.0,NaN,...,5.0,not found,english,movie/1211345,Done,NaN,NaN,NaN,NaN,NaN
2021,2173_movie,NaN,Tell Me,movie,drama,https://img1.hotstarext.com/image/upload/f_aut...,NaN,Hindi,0.0,NaN,...,4.0,not found,Hindi,movie/782000-tell-me,Done,NaN,NaN,NaN,NaN,NaN
2025,2050_movie,NaN,Neeyat,movie,"drama,mystery,tragedy,suspense,thriller,relati...",https://img1.hotstarext.com/image/upload/f_aut...,NaN,Hindi,0.0,NaN,...,54.0,not found,Hindi,movie/1187263-neeyat,Done,NaN,NaN,NaN,NaN,NaN
2026,2895_movie,NaN,Monarch of the Himalayas,movie,"nature,documentary",https://img1.hotstarext.com/image/upload/f_aut...,NaN,"English,Hindi,Tamil,Telugu",0.0,NaN,...,5.0,not found,english,movie/1187646-monarch-of-the-himalayas,Done,NaN,NaN,NaN,NaN,NaN

In [21]:
df.shape

(10562, 40)

In [ ]:
df[df['enriched_imdbid'] == 'not found'

8228

In [18]:
df1 = df[(df['enriched_tmdbid'].notna()) & (df['enriched_tmdbid'] != "not found") & (df['contenttype'] == 'movie')]

In [24]:
df1.head(140)

NameError: name 'df1' is not defined

In [20]:
df1['created_on'] ='2026-02-12 16:00:00'

C:\Users\M Rohith\AppData\Local\Temp\ipykernel_32364\795290805.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['created_on'] ='2026-02-12 16:00:00'

In [21]:
df1['created_on']

13644      2026-02-12 16:00:00
13645      2026-02-12 16:00:00
13646      2026-02-12 16:00:00
13647      2026-02-12 16:00:00
13648      2026-02-12 16:00:00
                  ...
1876255    2026-02-12 16:00:00
1876265    2026-02-12 16:00:00
1876267    2026-02-12 16:00:00
1876268    2026-02-12 16:00:00
1876270    2026-02-12 16:00:00
Name: created_on, Length: 10562, dtype: object

In [22]:
df1.reset_index(inplace=True, drop=True)

In [23]:
df1.head()

,contentid,cast,contentname,contenttype,genre,imgurl,keywords,language,parentid,parentname,...,enriched_rating,enriched_imdbid,enriched_language,enriched_tmdbid,enriched_meta_status,property_tags,portrait_url,landscape_url,contentpath,enriched_keywords
0,42805_movie,"Melissa Joan Hart,Dean Cain,Cynthia Gibb",Broadcasting Christmas,movie,"family,drama,comedy",https://li-img-cdn-lb.lionsgateplay.com/Lionsg...,NaN,English,0,NaN,...,5.0,tt6167116,english,movie/421759,Done,NaN,NaN,NaN,NaN,love
1,42781_movie,"Sam Rockwell,Phoebe Fox,Ben Schwartz,Peter Fer...",Blue Iguana - Trailer,movie,"action,crime,thriller,romance,comedy",https://li-img-cdn-lb.lionsgateplay.com/Lionsg...,NaN,English,0,NaN,...,5.6,tt2316479,english,movie/471429,Done,NaN,NaN,NaN,NaN,NaN
2,42750_movie,"Ben Foster,Jeffrey Grover,Christopher Amitrano...",Galveston - Trailer,movie,"action,crime,thriller,drama",https://li-img-cdn-lb.lionsgateplay.com/Lionsg...,NaN,English,0,NaN,...,6.2,tt2315596,english,movie/283601,Done,NaN,NaN,NaN,NaN,"hitman,revenge"
3,42933_movie,"Dylan O'Brien,Michael Keaton,Taylor Kitsch,Cha...",American Assassin,movie,"action,adventure",https://li-img-cdn-lb.lionsgateplay.com/Lionsg...,NaN,"Hindi,Telugu,Marathi,English,Tamil",0,NaN,...,6.2,tt1961175,english,movie/415842,Done,NaN,NaN,NaN,NaN,"revenge,violence"
4,42931_movie,"Nicolas Cage,Famke Janssen,Kevin Durand,Michae...",Primal,movie,"action,adventure",https://li-img-cdn-lb.lionsgateplay.com/Lionsg...,NaN,"English,Hindi,Telugu,Tamil",0,NaN,...,4.9,tt7394816,english,movie/500916,Done,NaN,NaN,NaN,NaN,assassin

In [25]:
df1.shape

(10562, 40)

In [26]:
df1['created_on']

0        2026-02-12 16:00:00
1        2026-02-12 16:00:00
2        2026-02-12 16:00:00
3        2026-02-12 16:00:00
4        2026-02-12 16:00:00
                ...
10557    2026-02-12 16:00:00
10558    2026-02-12 16:00:00
10559    2026-02-12 16:00:00
10560    2026-02-12 16:00:00
10561    2026-02-12 16:00:00
Name: created_on, Length: 10562, dtype: object

In [27]:
df1.to_csv('test_content.csv', index=False)

In [6]:
df[df['entiched_tmdbid'].isna()]

KeyError: 'entiched_tmdbid'

In [10]:
pip install browserforge

Defaulting to user installation because normal site-packages is not writeable
Collecting browserforge
  Downloading browserforge-1.2.4-py3-none-any.whl (37 kB)
Collecting apify_fingerprint_datapoints
  Downloading apify_fingerprint_datapoints-0.11.0-py3-none-any.whl (726 kB)
     -------------------------------------- 726.5/726.5 kB 9.2 MB/s eta 0:00:00
Collecting click
  Using cached click-8.3.1-py3-none-any.whl (108 kB)
Requirement already satisfied: colorama in c:\users\m rohith\appdata\roaming\python\python310\site-packages (from click->browserforge) (0.4.6)
Installing collected packages: click, apify_fingerprint_datapoints, browserforge
Successfully installed apify_fingerprint_datapoints-0.11.0 browserforge-1.2.4 click-8.3.1
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip available: 22.3.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [15]:
import requests

url = "https://api.duckduckgo.com/"
params = {
    "q": "RRR movie Rajamouli",
    "format": "json"
}

res = requests.get(url, params=params)
data = res.json()
print(data)

{'Abstract': '', 'AbstractSource': '', 'AbstractText': '', 'AbstractURL': '', 'Answer': '', 'AnswerType': '', 'Definition': '', 'DefinitionSource': '', 'DefinitionURL': '', 'Entity': '', 'Heading': '', 'Image': '', 'ImageHeight': '', 'ImageIsLogo': '', 'ImageWidth': '', 'Infobox': '', 'Redirect': '', 'RelatedTopics': [], 'Results': [], 'Type': '', 'meta': {'attribution': None, 'blockgroup': None, 'created_date': '2021-03-24', 'description': 'testing', 'designer': None, 'dev_date': '2021-03-24', 'dev_milestone': 'development', 'developer': [{'name': 'zt', 'type': 'duck.co', 'url': 'https://duck.co/user/zt'}], 'example_query': '', 'id': 'just_another_test', 'is_stackexchange': 0, 'js_callback_name': 'another_test', 'live_date': None, 'maintainer': {'github': ''}, 'name': 'Just Another Test', 'perl_module': 'DDG::Lontail::AnotherTest', 'producer': None, 'production_state': 'offline', 'repo': 'fathead', 'signal_from': 'just_another_test', 'src_domain': 'how about there', 'src_id': None, 'src_name': 'hi there', 'src_options': {'directory': '', 'is_fanon': 0, 'is_mediawiki': 0, 'is_wikipedia': 0, 'language': '', 'min_abstract_length': None, 'skip_abstract': 0, 'skip_abstract_paren': 0, 'skip_icon': 0, 'skip_image_name': 0, 'skip_qr': '', 'src_info': '', 'src_skip': ''}, 'src_url': 'Hello there', 'status': None, 'tab': 'is this source', 'topic': [], 'unsafe': None}}

In [52]:
import requests

API_KEY = 'eb0c0475'

def search_movies(movie_name):
    url = "http://www.omdbapi.com/"
    params = {
        "apikey": API_KEY,
        "s": movie_name  # search by title
    }
    response = requests.get(url, params=params)
    data = response.json()
    
    if data.get("Response") == "True":
        return data.get("Search", [])
    return []


def get_movie_details(imdb_id):
    url = "http://www.omdbapi.com/"
    params = {
        "apikey": API_KEY,
        "i": imdb_id  # fetch full details
    }
    response = requests.get(url, params=params)
    return response.json()


def find_movie_by_director(movie_name, director_name):
    search_results = search_movies(movie_name)
    
    matches = []
    
    for movie in search_results:
        imdb_id = movie.get("imdbID")
        details = get_movie_details(imdb_id)
        
        director = details.get("Director", "")
        
        # Match director (case-insensitive)
        if director_name.lower() in director.lower():
            matches.append(details)
    
    return matches


# Example usage
movie_name = "Patna wale dulhaniya le jayenge-Hindi"
director_name = "sanja"

results = find_movie_by_director(movie_name, director_name)

if results:
    print(results)
else:
    print("No matching movie found.")

No matching movie found.